# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-01-12 06:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='created_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='message_html',
            field=models.TextField(editable=False),
        ),
    ]
